"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class mot_state(object):

    __slots__ = ["timestamp", "q", "dq", "tau"]

    __typenames__ = ["int64_t", "double", "double", "double"]

    __dimensions__ = [None, [6], [6], [6]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.q = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.dq = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """
        self.tau = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: double[6] """

    def encode(self):
        buf = BytesIO()
        buf.write(mot_state._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>6d', *self.q[:6]))
        buf.write(struct.pack('>6d', *self.dq[:6]))
        buf.write(struct.pack('>6d', *self.tau[:6]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mot_state._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mot_state._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = mot_state()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.q = struct.unpack('>6d', buf.read(48))
        self.dq = struct.unpack('>6d', buf.read(48))
        self.tau = struct.unpack('>6d', buf.read(48))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if mot_state in parents: return 0
        tmphash = (0x8afab3dd98db18fe) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if mot_state._packed_fingerprint is None:
            mot_state._packed_fingerprint = struct.pack(">Q", mot_state._get_hash_recursive([]))
        return mot_state._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", mot_state._get_packed_fingerprint())[0]

